name: Run Karma Unit test on PR to main
on: [pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fantaski-app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm ci

      - name: Run Tests
        run: npm test